# Site settings
title: Diego Lopes
description: 'Business Card Page'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/foto.jpeg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'a376e81e40.js'

author:
  name: 'Diego Lopes Marques'
  email: lmsilva.diego@gmail.com
  #twitter_username: diegolms
  github_username:  diegolms
  linkedin_username:  diego-lopes-marques-09383723

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
